# Default values for ci-connector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image: docker.k8s.jobteaser.net/coretech/ci-connector:latest
pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# If not provided, secretName equals the Helm release name. You cna fix the secretName (if you want to share it between
# releases for instance)
# secretName:

script: |
  # run a ruby script
  puts 'this script should be placed in "script" parameters in helm chart'
  exit 1
