---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "clair.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: {{ template "clair.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "clair.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name | quote }}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            app.kubernetes.io/name: {{ .Values.networkPolicy.allowedNamespace }}
      # backward compatibility
      - namespaceSelector:
          matchLabels:
            name: {{ .Values.networkPolicy.allowedNamespace }}
      ports:
      - port: {{ .Values.service.externalApiPort }}
        protocol: TCP
        