apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clair.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: {{ template "clair.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
type: Opaque
data:
  config.yaml: |-
{{ include (print .Template.BasePath "/_config.yaml.tpl") . | b64enc | indent 4 }}
