apiVersion: v1
kind: Service
metadata:
  name: {{ template "clair.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app.kubernetes.io/name: {{ template "clair.fullname" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: "{{ .Chart.Name }}-api"
    port: {{ .Values.service.externalApiPort }}
    targetPort: {{ .Values.service.internalApiPort }}
    protocol: TCP
{{- if and (.Values.service.apiNodePort) (eq .Values.service.type "NodePort") }}
    nodePort: {{ .Values.service.apiNodePort }}
{{- end }}
  - name: "{{ .Chart.Name }}-health"
    port: {{ .Values.service.externalHealthPort }}
    targetPort: {{ .Values.service.internalHealthPort }}
    protocol: TCP
{{- if and (.Values.service.healthNodePort) (eq .Values.service.type "NodePort") }}
    nodePort: {{ .Values.service.healthNodePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ template "clair.fullname" . }}
