apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "mysql.fullname" . }}
  labels:
    app: {{ template "mysql.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "mysql.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "mysql.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        {{- if .Values.template.labels }}
{{ toYaml .Values.template.labels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.initData.enabled }}
      initContainers:
      - name: init-data
        image: {{ .Values.initData.image }}
        env:
        - name: OS_BUCKET
          value: {{ .Values.initData.objectStorage.bucket | quote }}
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.initData.objectStorage.secretKeyRefName }}
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.initData.objectStorage.secretKeyRefName }}
              key: secret-access-key
        command:
        {{- include "mysql.initData" . | indent 10 }}
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: mysql
        {{- if .Values.initData.restoreSql.enabled }}
        - name: data
          mountPath: /initdb
          subPath: initdb
        {{- end }}
      {{- if .Values.initData.restoreSql.enabled }}
      - name: restore-sql
        image: {{ .Values.image }}
        command:
        {{- include "mysql.restoreSql" . | indent 10 }}
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: data
          mountPath: /initdb
          subPath: initdb
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretKeyRefName }}
              key: root_password
        - name: MYSQL_DATABASE
          value: {{ .Values.database }}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretKeyRefName }}
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretKeyRefName }}
              key: password
      {{- end }}
      {{- end }}
      containers:
      - name: mysql
        image: {{ .Values.image }}
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretKeyRefName }}
              key: root_password
        - name: MYSQL_DATABASE
          value: {{ .Values.database }}
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretKeyRefName }}
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretKeyRefName }}
              key: password
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ template "mysql.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      storageClassName: {{ .Values.persistence.storageClassName | quote }}
      accessModes:
      - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
