---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "arachni.fullname" . }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: default
