---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ template "redis.fullname" . }}
  labels:
    app: {{ template "redis.fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ template "redis.fullname" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "redis.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        {{- if .Values.template.labels }}
{{ toYaml .Values.template.labels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets }}
      {{- end }}
      containers:
      #BEGIN redis
      - name: redis
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
         - /bin/sh
         - -c
         - |
           if [ ${HOSTNAME##*-} -eq 0 ]; then
             redis-server /etc/config/master.redis.conf
           else
             redis-server /etc/config/slave.redis.conf
           fi
        ports:
        - containerPort: {{ .Values.port }}
          name: db
        volumeMounts:
        - name: redis-config
          mountPath: /etc/config
        {{- if .Values.persistence.enabled }}
        - name: {{ template "redis.fullname" . }}
          mountPath: /data
        {{- else }}
        - name: empty-data
          mountPath: /data
        {{- end }}
      {{- if not .Values.persistence.enabled }}
      volumes:
      - name: empty-data
        emptyDir: {}
      {{- end }}
      #END redis

      #BEGIN sentinel
      # The sentinel monitors redis master
      - name: sentinel
        image: "{{ .Values.image }}"
        imagePullPolicy: {{ default "" .Values.imagePullPolicy | quote }}
        command:
          - /bin/sh
          - -c
          - |
            if [ ${HOSTNAME##*-} -eq 0 ]; then
              redis-server /etc/config/master.sentinel.conf --sentinel
            else
              redis-server /etc/config/slave.sentinel.conf --sentinel
            fi
        ports:
        - containerPort: {{ .Values.sentinel.port }}
          name: sentinel
        volumeMounts:
        - name: redis-config
          mountPath: /etc/config
      volumes:
        - name: redis-config
          configMap:
            name: {{ template "redis.fullname" . }}
      #END sentinel

  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
     name: {{ template "redis.fullname" . }}
     labels:
       app: {{ template "redis.fullname" . }}
       chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
       release: {{ .Release.Name }}
       heritage: {{ .Release.Service }}
    {{- if .Values.persistence.annotations }}
     annotations:
    {{ toYaml .Values.persistence.annotations | indent 10 }}
    {{- end}}
    spec:
      accessModes:
      - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
      storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
