apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus-org-runner-exporter.fullname" . }}
  labels:
    app: {{ template "prometheus-org-runner-exporter.name" . }}
    release: {{ .Release.Name }}
    {{- include "prometheus-org-runner-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "prometheus-org-runner-exporter.selectorLabels" . | nindent 4 }}
