{{- if .Values.rbac.enabled }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "datadog.fullname" . }}
rules:
  - nonResourceURLs:
    - "/version"  # Used to get apiserver version metadata
    - "/healthz"  # Healthcheck
    verbs: ["get"]

  - apiGroups: [""]
    resources:
      - "pods"
      - "nodes"
      - "namespaces"
      - "events"
      - "services"
    verbs: ["get", "list"]

  - apiGroups: [""]
    resources:
      - "configmaps"
    resourceNames: ["datadog-leader-elector"]
    verbs: ["get", "delete", "update"]

  - apiGroups: [""]
    resources:
      - "configmaps"
    verbs: ["create"]

  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list"]

  - apiGroups: ['extensions']
    resources:
      - "replicasets"
      - "daemonsets"
    verbs: ["get","list"]

  - apiGroups: ["apps"]
    resources:
      - "deployments"
    verbs: ["get", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "datadog.fullname" . }}
automountServiceAccountToken: true

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "datadog.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ template "datadog.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "datadog.fullname" . }}
  apiGroup: rbac.authorization.k8s.io

{{- end }}