
image: datadog/docker-dd-agent:latest

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "250m"

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  enabled: true
# If api_key is non empty, secret is created on the fly
#api_key:
secret_ref: datadog-integration
sd_backend: docker
namespace_regexp: ""
tags: ""
