#!/usr/bin/env sh

set -eu

output_dir="./charts"
index_url="https://jobteaser.github.com/charts"

mkdir -p $output_dir

find . -maxdepth 1 -type d | while read chart_dir; do
    if [ -f "$chart_dir/Chart.yaml" ]; then
        echo "packaging $chart_dir"

        helm package $chart_dir -d $output_dir
    fi
done

echo "indexing $output_dir"
helm repo index $output_dir --url $index_url
