apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ template "elasticsearch.name" . }}
    release: {{ .Release.Name }}
    tier: backend
    component: es
  ports:
  - protocol: {{ .Values.service.protocol }}
    name: {{ .Values.service.name }}
    port: {{ .Values.service.externalPort }}
    targetPort: {{ .Values.service.internalPort }}
