apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "elasticsearch.fullname" . }}
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "elasticsearch.name" . }}
      chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      {{- if .Values.template.labels }}
{{ toYaml .Values.template.labels | indent 6 }}
      {{- end }}
  serviceName: {{ template "elasticsearch.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        log/pattern: "^\\[[0-9]{4}-[0-9]{2}-[0-9]{2}"
        log/negate: "true"
        log/match: "after"
      labels:
        app: {{ template "elasticsearch.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        {{- if .Values.template.labels }}
{{ toYaml .Values.template.labels | indent 8 }}
        {{- end }}
    spec:
      {{- if .Values.initData.enabled }}
      initContainers:
      - name: init-data
        image: {{ .Values.initData.image }}
        env:
        - name: OS_PROVIDER
          value: {{ .Values.initData.objectStorage.provider | quote }}
        - name: OS_BUCKET
          value: {{ .Values.initData.objectStorage.bucket | quote }}
        - name: OS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Values.initData.objectStorage.secretKeyRefName }}
              key: access-key-id
        - name: OS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.initData.objectStorage.secretKeyRefName }}
              key: secret-access-key
        - name: OS_HOST
          value: {{ .Values.initData.objectStorage.host | quote }}
        command:
        {{- include "elasticsearch.initData" . | indent 10 }}
        volumeMounts:
        - name: data
          mountPath: /data
          subPath: elasticsearch
      {{- end }}
      containers:
      - name: {{ template "elasticsearch.name" . }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 9200
        resources:
{{ toYaml .Values.resources | indent 10 }}
        readinessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 10
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: 9200
          initialDelaySeconds: 90
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data/elasticsearch
          subPath: elasticsearch
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ template "elasticsearch.name" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
    spec:
      storageClassName: {{ .Values.persistence.storageClassName | quote }}
      accessModes:
      - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size }}
