apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubectl-oidc-helper.fullname" . }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  ca.crt: {{ .Values.app.cert }}
