apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "kubectl-oidc-helper.fullname" . }}
  labels:
    app: {{ template "kubectl-oidc-helper.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "kubectl-oidc-helper.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.internalPort }}
          args:
          - "--issuer={{ .Values.app.issuer }}"
          - "--client-secret={{ .Values.app.clientSecret }}"
          - "--k8s-name={{ .Values.app.k8sName }}"
          - "--k8s-api={{ .Values.app.k8sApi }}"
          - "--listen=http://0.0.0.0:5555"
          - "--redirect-uri={{ .Values.app.redirectUri }}"

          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
