# Default values for mysql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

database: mysql
# We are looking for root_password, username and password in this secret.
secretKeyRefName: mysql

image: mysql:5.6

initData:
  enabled: false
  image: jobteaser/awscli:latest
  # datafile:
  objectStorage: {}
    # To define object storage values, uncomment the following lines, adjust them as
    # necessary, and remove the curly braces after 'objectStorage:'.
    # bucket:
    # We are looking for access-key-id and secret-access-key in this secret.
    # secretKeyRefName:

service:
  name: mysql
  type: ClusterIP
  externalPort: 3306
  internalPort: 3306

persistence:
  storageClassName: default
  accessMode: ReadWriteOnce
  # size: 8Gi

template:
  labels: {}
    # To define specific labels, uncomment the following lines, adjust them as
    # necessary, and remove the curly braces after 'labels:'.
    # tier: db
    # component: mysql

networkPolicy:
    ## Enable creation of NetworkPolicy resources.
    ##
    enabled: false

    ## The Policy model to apply. When set to false, only pods with the correct
    ## client label will have network access to the port PostgreSQL is listening
    ## on. When true, PostgreSQL will accept connections from any source
    ## (with the correct destination port).
    ##
    # allowExternal:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
