---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubernetes-filebeat.fullname" . }}-config
  labels:
    {{- if .Values.cluster_service }}
    k8s-app: {{ template "kubernetes-filebeat.fullname" . }}
    kubernetes.io/cluster-service: "true"
    {{- end }}
    app: {{ template "kubernetes-filebeat.name" . }}
    chart: {{ template "kubernetes-filebeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        # Mounted `filebeat-prospectors` configmap:
        path: ${path.config}/prospectors.d/*.yml
        # Reload prospectors configs as they change:
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        # Reload module configs as they change:
        reload.enabled: false
    processors:
      - add_cloud_metadata:

    output.elasticsearch:
      hosts: ['{{ .Values.app.elasticsearch_host }}']
      {{- if .Values.app.elastic_auth_enabled }}
      username: {{ .Values.app.elasticsearch_username }}
      password: {{ .Values.app.elasticsearch_password }}
      {{- end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubernetes-filebeat.fullname" . }}-prospectors
  labels:
    {{- if .Values.cluster_service }}
    k8s-app: {{ template "kubernetes-filebeat.fullname" . }}
    kubernetes.io/cluster-service: "true"
    {{- end }}
    app: {{ template "kubernetes-filebeat.name" . }}
    chart: {{ template "kubernetes-filebeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
      multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
      multiline.negate: false
      multiline.match: after
