apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "kubernetes-filebeat.fullname" . }}-nodes
  labels:
    app: {{ template "kubernetes-filebeat.name" . }}
    chart: {{ template "kubernetes-filebeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    checksum/config: {{ include "conf_node" . | sha256sum }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "kubernetes-filebeat.name" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        profile: node
      annotations:
        checksum/config: {{ include "conf_node" . | sha256sum }}
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      nodeSelector:
        'kubernetes.io/role': node
      tolerations:
        - operator: "Exists"
      containers:
      - name: filebeat
        image: "{{ .Values.app.node_image }}"
        imagePullPolicy: Always
        args: [ "-c", "/etc/filebeat.yml", "-e" ]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data/
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ template "kubernetes-filebeat.fullname" . }}-config-node
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: data
        hostPath:
          type: DirectoryOrCreate
          path: /opt/filebeat

---
# Node config
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubernetes-filebeat.fullname" . }}-config-node
  labels:
    app: {{ template "kubernetes-filebeat.name" . }}
    chart: {{ template "kubernetes-filebeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  filebeat.yml: |-
{{- include "conf_node" . | indent 4 }}
