---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: {{ template "kubernetes-filebeat.fullname" . }}-master
  labels:
    app: {{ template "kubernetes-filebeat.name" . }}
    chart: {{ template "kubernetes-filebeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "kubernetes-filebeat.name" . }}
        chart: {{ template "kubernetes-filebeat.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        profile: master
      annotations:
        checksum/config: {{ include "conf_master" . | sha256sum }}
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      nodeSelector:
        'kubernetes.io/role': master
      tolerations:
      - key: 'node-role.kubernetes.io/master'
        effect: NoSchedule
      containers:
      - name: filebeat
        image: "{{ .Values.app.master_image }}"
        imagePullPolicy: Always
        args: [ "-c", "/etc/filebeat.yml", "-e" ]
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data/
        - name: varlog
          mountPath: /var/log/
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: {{ template "kubernetes-filebeat.fullname" . }}-config-master
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          type: DirectoryOrCreate
          path: /opt/filebeat

---
# Node config
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kubernetes-filebeat.fullname" . }}-config-master
  labels:
    app: {{ template "kubernetes-filebeat.name" . }}
    chart: {{ template "kubernetes-filebeat.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  filebeat.yml: |-
{{- include "conf_master" . | indent 4 }}
