apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "minio.fullname" . }}
  labels:
    app: {{ template "minio.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ template "minio.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ template "minio.fullname" . }}-pvc
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: ["server", "/storage"]
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretKeyRefName }}
              key: access-key-id
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secretKeyRefName }}
              key: secret-access-key
        ports:
          - containerPort: 9000
        resources:
{{ toYaml .Values.resources | indent 12 }}
        volumeMounts:
          - name: storage
            mountPath: "/storage"
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
