redis:
  port: 6379
  replicaCount: 3
  diskSize: 8Gi
sentinel:
  quorum: 2
  port: 26379

image: "redis:3.2"

template:
  labels: {}
    # To define specific labels, uncomment the following lines, adjust them as
    # necessary, and remove the curly braces after 'labels:'.
    # tier: db
    # component: redis
